CREATE DATABASE IF NOT EXISTS demo;
CREATE USER IF NOT EXISTS 'demouser'@'localhost' IDENTIFIED BY 'Str0ngPass!123';
GRANT ALL PRIVILEGES ON demo.* TO 'demouser'@'localhost';
FLUSH PRIVILEGES;

USE demo;
CREATE TABLE IF NOT EXISTS todos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  is_done TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
